name: 📦 Compile and Run on Release

on:
  push:
    paths:
      - 'VERSION'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile the code
      run: make

    - name: Get commit message
      id: get-commit-message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Get version
      id: get-release-version
      run: echo "VERSION=v$(cat VERSION)" >> $GITHUB_ENV
    
    - name: Calculate file hash
      id: hash
      run: |
        sha256sum syn-flood > syn-flood.sha256

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: ${{ env.COMMIT_MESSAGE }}
        draft: false
        prerelease: false

    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          syn-flood
          syn-flood.sha256
        tag_name: ${{ env.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
